name: clear_finance_2po
description: A Flutter mobile finance tracking application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  
  # State Management
  provider: ^6.1.1
  
  # Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  
  # HTTP & API
  http: ^1.1.0
  
  # Date & Time
  intl: ^0.20.2
  uuid: ^4.0.0
  # Charts
  fl_chart: ^1.1.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # assets:
  #   - images/
  #   - icons/
